app/webapp/poll/urls.py
from django.urls import path
from rest_framework import routers

from .views import VoteViewSet, RoomViewSet, CommentViewSet,SlideViewSet
from . import views

app_name = 'poll'

router = routers.DefaultRouter()
router.register(r'votes', VoteViewSet)
router.register(r'rooms', RoomViewSet)
router.register(r'comments', CommentViewSet)
router.register(r'slides', SlideViewSet)

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:room_id>/listener_a/', views.listener_a, name='listener_a'),
    path('<int:room_id>/listener_b/', views.listener_b, name='listener_b'),
    path('<int:room_id>/speaker-start/', views.speaker_start, name='speaker_start'),
    path('<int:room_id>/speaker/', views.speaker, name='speaker'),
    path('<int:room_id>/speaker/res', views.speaker_res, name='speaker_res'),
    path('<int:room_id>/speaker/change-status', views.change_status, name='change-status'),
]

app/webapp/webapp/urls.py
from django.contrib import admin
from django.urls import path, include

from poll.urls import router as poll_router

urlpatterns = [
    path('admin/', admin.site.urls),
    path('poll/', include('poll.urls')),
    path('api/', include(poll_router.urls))
]

app/webapp/poll/models.py
from django.db import models


class RoomTable(models.Model):
    """
    ルームのモデル
    """
    # ルーム名
    room_name = models.CharField(max_length=32)
    # パスワード
    password = models.CharField(max_length=32)
    # リスナーの人数
    num_listener = models.IntegerField(default=0)

    def __str__(self):
        return self.room_name


class SlideTable(models.Model):
    """
    スライドのモデル
    """
    # スライド番号
    slide_no = models.IntegerField(default=0)
    # スライドの開始時間
    start_time = models.DateTimeField('slide start time')
    # スライドの終了時間
    end_time = models.DateTimeField('slide end time', blank=True, null=True)
    # ルームID
    room_id = models.ForeignKey(RoomTable, on_delete=models.CASCADE)


class VoteTable(models.Model):
    """
    票のモデル
    """
    # 票の種類
    vote_type = models.IntegerField()
    # 票の送信時刻
    vote_time = models.DateTimeField('date published')
    # 投票時のスライドID
    slide_id = models.ForeignKey(SlideTable, on_delete=models.CASCADE)


class CommentTable(models.Model):
    """
    コメントのモデル
    """
    # コメントの内容
    comment_text = models.CharField(max_length=256)
    # コメントの送信時刻
    comment_time = models.DateTimeField('date published')
    # コメント送信時のスライドID
    slide_id = models.ForeignKey(SlideTable, on_delete=models.CASCADE)

app/webapp/poll/forms.py
from django.forms import ModelForm
from .models import RoomTable


class RoomForm(ModelForm):
    """ルームのフォーム"""
    class Meta:
        model = RoomTable
        fields = ('room_name',)

app/webapp/poll/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from rest_framework import viewsets
from django.urls import reverse
from django.db.models import Max
from django.utils import timezone
from datetime import timedelta
from .models import VoteTable, RoomTable, CommentTable, SlideTable
from .serializer import VoteSerializer, RoomSerializer, CommentSerializer, SlideSerializer
import re
import datetime
from .listener_button import button1, button2, button3, comment_submit
from .forms import RoomForm


def index(request):
    room = RoomTable()
    if request.method == 'POST':
        form = RoomForm(request.POST, instance=room)
        if form.is_valid():
            room = form.save(commit=False)
            input_name = room.room_name
            if request.POST['action'] == 'make_room':
                # 同じ名前の部屋がすでにあればエラーメッセージを出させる
                if RoomTable.objects.filter(room_name__exact=input_name).exists():
                    return render(request, 'poll/index.html', {
                        'form': form,
                        'error_message': '"' + input_name + '"はすでに存在します．'
                    })
                else:
                    room.save()
                    return HttpResponseRedirect(reverse('poll:speaker_start', args=(room.id,)))
            elif request.POST['action'] == 'view_results':
                view = RoomTable.objects.filter(room_name__exact=input_name).first()
                if view is None:
                    return render(request, 'poll/index.html', {
                        'form': form,
                        'error_message': '"' + input_name + '"は存在しません．'
                    })
                else:
                    return HttpResponseRedirect(reverse('poll:speaker_res', args=(view.id,)))
            elif request.POST['action'] == 'join_room':
                join = RoomTable.objects.filter(room_name__exact=input_name).first()
                if join is None:
                    return render(request, 'poll/index.html', {
                        'form': form,
                        'error_message': '"' + input_name + '"は存在しません．'
                    })
                else:
                    join.num_listener += 1
                    join.save()
                    return HttpResponseRedirect(reverse('poll:listener_a', args=(join.id,)))
            else:
                pass
    else:
        form = RoomForm(instance=room)

    return render(request, 'poll/index.html', {'form': form})


# 一回目のリスナーページ読み込み
def listener_a(request, room_id):
    template_name = 'poll/listener_a.html'

    if request.method == 'POST':
        input_comment = request.POST.get('input_comment')
        if 'button_1' in request.POST:
            # ボタン1がクリックされた場合の処理
            slide_info = button1(room_id)
        elif 'button_2' in request.POST:
            # ボタン2がクリックされた場合の処理
            slide_info = button2(room_id)
        elif 'button_3' in request.POST:
            # ボタン3がクリックされた場合の処理
            slide_info = button3(room_id)
        elif 'button_submit' in request.POST:
            slide_info = comment_submit(input_comment, room_id)

        #  1:vote
        #  2:comment
        # -1:講義開始前
        # -2:講義終了後
        if slide_info == 1:
            template_name = 'poll/listener_b.html'
        elif slide_info == -1:
            return render(request, template_name, {
                'room_id': room_id,
                'error_message': '講義が始まっていません'
            })
        elif slide_info == -2:
            return render(request, template_name, {
                'room_id': room_id,
                'error_message': '講義が終わっています'
            })

    return render(request, template_name, {'room_id': room_id})


# 二回目以降のリスナーページ読み込み
def listener_b(request, room_id):
    template_name = 'poll/listener_a.html'

    if request.method == 'POST':
        input_comment = request.POST.get('input_comment')
        if 'button_1' in request.POST:
            # ボタン1がクリックされた場合の処理
            slide_info = button1(room_id)
        elif 'button_2' in request.POST:
            # ボタン2がクリックされた場合の処理
            slide_info = button2(room_id)
        elif 'button_3' in request.POST:
            # ボタン3がクリックされた場合の処理
            slide_info = button3(room_id)
        elif 'button_submit' in request.POST:
            slide_info = comment_submit(input_comment, room_id)

        #  1:vote
        #  2:comment
        # -1:講義開始前
        # -2:講義終了後
        if slide_info == 1:
            template_name = 'poll/listener_b.html'
        elif slide_info == -1:
            return render(request, template_name, {
                'room_id': room_id,
                'error_message': '講義が始まっていません'
            })
        elif slide_info == -2:
            return render(request, template_name, {
                'room_id': room_id,
                'error_message': '講義が終わっています'
            })

    return render(request, template_name, {'room_id': room_id})


def speaker_start(request, room_id):
    template_name = 'poll/speaker-start.html'

    return render(request, template_name, {'room_id': room_id})


def speaker(request, room_id):
    template_name = 'poll/speaker.html'

    return render(request, template_name, {'room_id': room_id})


def speaker_res(request, room_id):
    template_name = 'poll/speaker_res.html'

    # --------------------グラフ機能--------------------
    # スライドの枚数，room_idの中で一番大きいslide_no
    slide_num = SlideTable.objects.filter(room_id_id__exact=room_id).aggregate(Max('slide_no'))['slide_no__max']

    slide_list = []  # slide_1, slide_2, ... slide_n
    time_list = []  # 時間(x軸)
    data1_list = []  # わかる
    data2_list = []  # しってる
    data3_list = []  # わからん
    regex_time = r'\d\d-\d\d \d\d:\d\d:\d\d'
    regex_date_time = r'\d\d\d\d-\d\d-\d\d \d\d:\d\d:\d\d'
    time_divide = 10  # グラフの集計をする時の区切りの秒数.例えばtime_divide=10の場合，グラフは最低10秒の間隔ができる．

    for i in range(1, int(slide_num) + 1):
        # スライドタイトル(slide_i)のリストに追加
        slide_list.append('slide_' + str(i))

        # スライドごとのデータを作成
        slide_start_time = SlideTable.objects.filter(room_id_id__exact=room_id, slide_no__exact=i).first().start_time
        slide_st_time = re.search(regex_time, str(timezone.localtime(slide_start_time))).group()
        slide_end_time = SlideTable.objects.filter(room_id_id__exact=room_id, slide_no__exact=i).first().end_time
        if slide_end_time is None:  # 講義中にHOMEに戻りView resultsを押すと起こる
            slide_end_time = timezone.now()
        slide_ed_time = re.search(regex_time, str(timezone.localtime(slide_end_time))).group()
        times = ['x', slide_st_time]
        data1s = ['分かった', 0]  # スライド開始時はすべて0票
        data2s = ['もう知ってる', 0]
        data3s = ['分からない', 0]
        data1sum = 0
        data2sum = 0
        data3sum = 0
        time_temp = slide_start_time
        plus_time_div = time_temp + datetime.timedelta(seconds=time_divide)

        # time_divideごとのデータを作成する
        while plus_time_div < slide_end_time:
            # room_id_id == room_id && slide_no == i && time_temp <= vote_time < plus_time_div
            votes = VoteTable.objects \
                .filter(slide_id__room_id_id__exact=room_id, slide_id__slide_no__exact=i,
                        vote_time__gte=time_temp, vote_time__lt=plus_time_div) \
                .order_by('vote_time')
            for vote in votes:
                if vote.vote_type == 1:
                    data1sum += 1
                elif vote.vote_type == 2:
                    data2sum += 1
                elif vote.vote_type == 3:
                    data3sum += 1
                else:
                    pass
            times.append(re.search(regex_time, str(timezone.localtime(plus_time_div))).group())
            append_data(data1s, data2s, data3s, data1sum, data2sum, data3sum)
            data1sum = 0
            data2sum = 0
            data3sum = 0
            time_temp = plus_time_div
            plus_time_div += datetime.timedelta(seconds=time_divide)

        # スライド終了
        votes = VoteTable.objects \
            .filter(slide_id__room_id_id__exact=room_id, slide_id__slide_no__exact=i,
                    vote_time__gte=time_temp, vote_time__lte=slide_end_time) \
            .order_by('vote_time')
        for vote in votes:
            if vote.vote_type == 1:
                data1sum += 1
            elif vote.vote_type == 2:
                data2sum += 1
            elif vote.vote_type == 3:
                data3sum += 1
            else:
                pass
        times.append(slide_ed_time)
        append_data(data1s, data2s, data3s, data1sum, data2sum, data3sum)
        # スライドのデータを追加
        time_list.append(times)
        append_data(data1_list, data2_list, data3_list, data1s, data2s, data3s)

    # --------------------コメント機能--------------------
    # room_idの部屋の全データ取得
    comments = CommentTable.objects.filter(slide_id__room_id_id__exact=room_id).order_by('comment_time')
    comment_dic_list = []
    for comment in comments:
        dic = dict()
        dic['slide'] = comment.slide_id.slide_no
        date_time_str = re.search(regex_date_time, str(timezone.localtime(comment.comment_time))).group()
        date_time_str = date_time_str.replace('-', '/')
        dic['time'] = date_time_str
        dic['text'] = comment.comment_text
        comment_dic_list.append(dic)

    return render(request, template_name, {
        'slide_list': slide_list,  # スライドのタイトル'slide_n'のリスト，要素数はスライドの枚数
        'slide_num': slide_num,  # スライドの枚数
        'time_list': time_list,
        'data1_list': data1_list,
        'data2_list': data2_list,
        'data3_list': data3_list,
        'comment_dic_list': comment_dic_list
    })


def append_data(a, b, c, x, y, z):
    a.append(x)
    b.append(y)
    c.append(z)


def change_status(request, room_id):
    room_info = RoomTable.objects.filter(id=room_id).first()

    if request.POST['action'] == 'start-lec':
        SlideTable.objects.create(slide_no=1, start_time=timezone.now(), room_id=room_info)

app/webapp/poll/templates/poll/index.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block title %}
    Home
{% endblock %}

{# メインコンテンツ #}
{% block content %}
    <div class="jumbotron jumbotron-fluid">
        <div class="container-fluid jumbotron-container">
        <div class="jumbotron-fluid">
            <div class="logo">
            </div>
        </div>
            <form action="{% url 'poll:index' %}" method="post">
                {% csrf_token %}
                <div class="form-row">
                    <input type="text" class="form-control" placeholder="Room Name">
                </div>
                {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
                <button class="btn btn-outline-primary btn-lg" type='submit' name='action' value='make_room'>
                    Make room
                </button>
                <button class="btn btn-outline-primary btn-lg" type='submit' name='action' value='view_results'>
                    View results
                </button>
                <button class="btn btn-outline-primary btn-lg" type='submit' name='action' value='join_room'>
                    Join room
                </button>
            </form>
        </div>
    </div>

    {# Enterを無効にする #}
    <script>
        $(function () {
            $("input").keydown(function (e) {
                if ((e.which && e.which === 13) || (e.keyCode && e.keyCode === 13)) {
                    return false;
                } else {
                    return true;
                }
            });
        });
    </script>
{% endblock %}

app/webapp/poll/templates/poll/listener_a.html
{% extends 'base.html' %}
{% block title %}
    Listener
{% endblock %}

{# メインコンテンツ #}
{% block content %}
    <div class="listener-group">
        {% if error_message %}
            <h2 style="color: red;">
                <strong>{{ error_message }}</strong>
            </h2>
        {% endif %}
        <form action="{% url 'poll:listener_a' room_id %}" method="post">
            <div class="row">
                {% csrf_token %}
                <div class="col-lg" style="text-align: center">
                    <h3>わかった</h3>
                    <button class="btn btn-circle btn-understand" name="button_1">
                    </button>
                </div>
                <div class="col-lg" style="text-align: center">
                    <h3>もう知っている</h3>
                    <button class="btn btn-circle btn-have-known" name="button_2">
                    </button>
                </div>
                <div class="col-lg" style="text-align: center">
                    <h3>わからない</h3>
                    <button class="btn btn-circle btn-not-understand" name="button_3">
                    </button>
                </div>
            </div>
        </form>
        <form action="{% url 'poll:listener_a' room_id %}" method="post">
            {% csrf_token %}
            <div class="input-group">
                <input type="text" class="form-control" placeholder="Input comment" size="100" name="input_comment">
                <div class="input-group-btn">
                    <button class="btn btn-default" type="submit" style="background-color: white"
                            name="button_submit">
                        <i class="far fa-paper-plane"></i>
                    </button>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

app/webapp/poll/templates/poll/listener_b.html
{% extends 'base.html' %}
{% block title %}
    Listener
{% endblock %}

{# メインコンテンツ #}
{% block content %}
    <div class="listener-group">
        <form name="vote" action="{% url 'poll:listener_b' room_id %}" method="post">
            <div class="row">
                {% csrf_token %}
                <div class="col-lg" style="text-align: center">
                    <h3>わかった</h3>
                    <button class="btn btn-circle btn-understand" name="button_1" id="btn_1">
                    </button>
                </div>
                <div class="col-lg" style="text-align: center">
                    <h3>もう知っている</h3>
                    <button class="btn btn-circle btn-have-known" name="button_2" id="btn_2">
                    </button>
                </div>
                <div class="col-lg" style="text-align: center">
                    <h3>わからない</h3>
                    <button class="btn btn-circle btn-not-understand" name="button_3" id="btn_3">
                    </button>
                </div>
            </div>
        </form>
        <form action="{% url 'poll:listener_b' room_id %}" method="post">
            {% csrf_token %}
            <div class="input-group">
                <input type="text" class="form-control" placeholder="Input comment" size="100" name="input_comment">
                <div class="input-group-btn">
                    <button class="btn btn-default" type="submit" style="background-color: white"
                            name="button_submit">
                        <i class="far fa-paper-plane"></i>
                    </button>
                </div>
            </div>
        </form>
    </div>

    <script>
        window.onload = function () {
            $("#btn_1").attr('disabled', true);
            $("#btn_2").attr('disabled', true);
            $("#btn_3").attr('disabled', true);
            console.log("disableにしたよ");
            setTimeout(function () {
                $("#btn_1").attr('disabled', false);
                $("#btn_2").attr('disabled', false);
                $("#btn_3").attr('disabled', false);
                console.log("ableにしたよ");
            }, 60000);
        };
    </script>
{% endblock %}

app/webapp/poll/templates/poll/speaker-start.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Ready
{% endblock %}
{% block head %}
    <link rel="stylesheet" type="text/css" href="{% static 'poll/css/epoch.min.css' %}">
    <script src="{% static 'poll/js/d3-v3.5.17.min.js' %}" charset="utf-8"></script>
    <script src="{% static 'poll/js/epoch.min.js' %}"></script>
{% endblock %}

{# メインコンテンツ #}
{% block content %}

    {#  票数の割合のメーター  #}
    <div class="container-fluid">
        <div class="row" style="position: center">
            <div class="col-lg" style="padding: 0%">
                <div class="container-meter">
                    <div id="understand_gauge" class="understand">
                        <h3>わかった</h3>
                        <div class="epoch gauge-medium"></div>
                    </div>
                </div>
            </div>
            <div class="col-lg" style="padding: 0%">
                <div class="container-meter">
                    <div id="have_known_gauge" class="have_known">
                        <h3>もう知ってる</h3>
                        <div class="epoch gauge-medium"></div>
                    </div>
                </div>
            </div>
            <div class="col-lg" style="padding: 0%">
                <div class="container-meter">
                    <div id="not_understand_gauge" class="not_understand">
                        <h3>わからない</h3>
                        <div class="epoch gauge-medium"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container-fluid jumbotron-container">
        {# コメント一覧表 #}
        <div class="container-table">
            <table class="table table-striped table-bordered">
                <thead>
                <tr>
                    <th scope="col" class="th-slide">スライド</th>
                    <th scope="col" class="th-time">時刻</th>
                    <th scope="col" class="th-comments">内容</th>
                </tr>
                </thead>
                <tbody id="comment_info">
                </tbody>
            </table>
        </div>
    </div>

    <div class="container-fluid jumbotron-container">
        <div class="slide-group-buttons">
            <form action="{% url 'poll:change-status' room_id %}" method="post">
                {% csrf_token %}
                <button class="btn btn-outline-primary btn-lg" type='submit' name='action' value='start-lec'>
                    講義開始
                </button>
            </form>
        </div>
    </div>

    <script>
        $('#understand_gauge .epoch').epoch({
            type: 'time.gauge',
            value: 0.0
        });

        $('#have_known_gauge .epoch').epoch({
            type: 'time.gauge',
            value: 0.0
        });

        $('#not_understand_gauge .epoch').epoch({
            type: 'time.gauge',
            value: 0.0
        });
    </script>

{% endblock %}

app/webapp/poll/templates/poll/speaker_res.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Results
{% endblock %}
{% block head %}
    <link rel="stylesheet" href="{% static 'poll/css/c3-v0.4.18.min.css' %}"/>
    <script src="{% static 'poll/js/d3-v3.5.17.min.js' %}" charset="utf-8"></script>
    <script src="{% static 'poll/js/c3-v0.4.18.min.js' %}"></script>
{% endblock %}

{# メインコンテンツ #}
{% block content %}
    <div class="container-head" style="color: #19C5FF">
        <h1>Listener's Voices</h1>
    </div>

    <div class="container-group-graph">
        <a href="{% url 'poll:index' %}" class="btn btn-outline-secondary btn-lg">
            Homeに戻る
        </a>

        {# スライド数のグラフをバインドする要素の準備 #}
        <div class="container-graph">
            {% for i in slide_list %}
                <h3 style="text-align: center">{{ i }}</h3>
                <div id={{ i }}></div>
            {% endfor %}
        </div>
    </div>

    {# コメント一覧表 #}
    <div class="container-table">
        <table class="table table-striped table-bordered">
            <thead>
            <tr>
                <th scope="col" class="th-slide">スライド</th>
                <th scope="col" class="th-time">時刻</th>
                <th scope="col" class="th-comments">内容</th>
            </tr>
            </thead>
            <tbody>
            {% for comment in comment_dic_list %}
                <tr>
                    <td class="td-slide">{{ comment.slide }}</td>
                    <td class="td-time">{{ comment.time }}</td>
                    <td class="td-comments">{{ comment.text }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

    <div class="container-home">
        <a href="{% url 'poll:index' %}" class="btn btn-outline-secondary btn-lg">
            Homeに戻る
        </a>
    </div>

    <script>
        let datax = [];
        let data1 = [];
        let data2 = [];
        let data3 = [];

        let data_var = [];
        let counter = 0;

        {# x軸データ #}
        {% for list in time_list %}
            counter = {{ forloop.counter0 }};
            data_var[counter] = [];
            {% for v in list %}
                data_var[counter].push('{{ v }}');
            {% endfor %}
            datax.push(data_var[counter]);
        {% endfor %}

        {# 分かったデータ #}
        {% for list in data1_list %}
            counter = {{ forloop.counter0 }};
            data_var[counter] = [];
            {% for v in list %}
                data_var[counter].push('{{ v }}');
            {% endfor %}
            data1.push(data_var[counter]);
        {% endfor %}

        {# もう知ってるデータ #}
        {% for list in data2_list %}
            counter = {{ forloop.counter0 }};
            data_var[counter] = [];
            {% for v in list %}
                data_var[counter].push('{{ v }}');
            {% endfor %}
            data2.push(data_var[counter]);
        {% endfor %}

        {# 分からないデータ #}
        {% for list in data3_list %}
            counter = {{ forloop.counter0 }};
            data_var[counter] = [];
            {% for v in list %}
                data_var[counter].push('{{ v }}');
            {% endfor %}
            data3.push(data_var[counter]);
        {% endfor %}

        {# 折れ線グラフ作成 #}
        for (let i = 0; i < {{ slide_num }}; i++) {
            let array1 = data1[i].slice(1, data1[i].length - 1);
            let array2 = data2[i].slice(1, data2[i].length - 1);
            let array3 = data3[i].slice(1, data3[i].length - 1);
            let max_array = [Math.max(...array1), Math.max(...array2), Math.max(...array3)];
            let max_val = Math.max(...max_array);
            let y_tick_val = [];
            for (let i = 0; i < max_val + 1; i++) {
                y_tick_val.push(i);
            }

            c3.generate({
                bindto: "#slide_" + (i + 1),
                padding: {
                    right: 20
                },
                data: {
                    x: 'x',
                    xFormat: '%m-%d %H:%M:%S',
                    columns: [
                        datax[i],
                        data1[i],
                        data2[i],
                        data3[i]
                    ],
                    types: {
                        分かった: 'area',
                        もう知ってる: 'area',
                        分からない: 'area'
                    }
                },
                axis: {
                    x: {
                        type: 'timeseries',
                        tick: {
                            format: '%m-%d %H:%M:%S'
                        }
                    },
                    y: {
                        tick: {values: y_tick_val}
                    }
                },
                grid: {
                    x: {
                        show: false
                    },
                    y: {
                        show: true
                    }
                }
            });
        }
    </script>
{% endblock %}